=== Aboubakry-BA/Messagerie_XML/messagerie.dtd
<!-- Structure pour stocker les données d'un service de messagerie en ligne de type WhatsApp -->
<!ELEMENT messagerie (utilisateur+, groupe*, message*)>

<!-- Définition d'un utilisateur avec un profil -->
<!ELEMENT utilisateur (profil, contacts)>
<!ATTLIST utilisateur idUtilisateur ID #REQUIRED>

<!-- Informations de profil de l'utilisateur -->
<!ELEMENT profil (nom, numeroDeTelephone, imageProfil, statut)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT numeroDeTelephone (#PCDATA)>
<!ELEMENT imageProfil (#PCDATA)>
<!ELEMENT statut (#PCDATA)>

<!-- Contacts de l'utilisateur -->
<!ELEMENT contacts (contact*)>
<!ELEMENT contact EMPTY>
<!ATTLIST contact refIdUtilisateur IDREF #REQUIRED>

<!-- Définition d'un groupe avec un nom, des membres et des messages -->
<!ELEMENT groupe (nomGroupe, membres, messages*)>
<!ATTLIST groupe idGroupe ID #REQUIRED>
<!ELEMENT nomGroupe (#PCDATA)>
<!ELEMENT membres (membre*)>
<!ELEMENT membre EMPTY>
<!ATTLIST membre refIdUtilisateur IDREF #REQUIRED>
<!ELEMENT messages (refIdMessage*)>

<!-- Référence à un message dans un groupe -->
<!ELEMENT refIdMessage EMPTY>
<!ATTLIST refIdMessage refId IDREF #REQUIRED>

<!-- Définition d'un message avec un contenu, un horodatage, un expéditeur, un destinataire et un
message cité optionnel -->
<!ELEMENT message (contenu, expediteur, horodatage, destinataire, citation?)>
<!ATTLIST message
    idMessage ID #REQUIRED
    typeContenu (texte | audio | fichier) #REQUIRED
    statut (envoye | recu | lu) #REQUIRED>
<!ELEMENT contenu (#PCDATA)>
<!ELEMENT expediteur (#PCDATA)>

<!-- Expéditeur du message -->
<!ATTLIST expediteur refIdUtilisateur IDREF #REQUIRED>

<!ELEMENT horodatage (#PCDATA)>
<!ELEMENT destinataire (#PCDATA)>

<!-- Destinataire du message -->
<!ATTLIST destinataire
    refIdUtilisateur IDREF #IMPLIED
    refIdGroupe IDREF #IMPLIED>

<!-- Citation d'un autre message -->
<!ELEMENT citation EMPTY>
<!ATTLIST citation refIdMessage IDREF #REQUIRED>

=== Aboubakry-BA/Messagerie_XML/messagerie.xml
<?xml version="1.0"?>
<!-- <?xml version="1.0"?>
<!DOCTYPE messagerie SYSTEM "messagerie.dtd">
<messagerie> -->
<messagerie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="messagerie.xsd">
    <utilisateur idUtilisateur="u1">
        <!-- Utilisateur 1 : Aboubakry -->
        <profil>
            <nom>Aboubakry BA</nom>
            <numeroDeTelephone>774954357</numeroDeTelephone>
            <imageProfil>http://aboubakryba.jpeg</imageProfil>
            <statut>Hors Service</statut>
        </profil>
        <contacts>
            <!-- Aboubakry a Modou comme contact -->
            <contact refIdUtilisateur="u2" />
            <!-- Aboubakry a Samba comme contact -->
            <contact refIdUtilisateur="u3" />
        </contacts>
    </utilisateur>

    <utilisateur idUtilisateur="u2">
        <!-- Utilisateur 2 : Modou -->
        <profil>
            <nom>Modou Fall</nom>
            <numeroDeTelephone>776455746</numeroDeTelephone>
            <imageProfil>http://profiles/modou.jpg</imageProfil>
            <statut>Occup&#xE9;</statut>
        </profil>
        <contacts>
            <!-- Modou a Aboubakry comme contact -->
            <contact refIdUtilisateur="u1" />
            <!-- Modou a Samba comme contact -->
            <contact refIdUtilisateur="u3" />
        </contacts>
    </utilisateur>

    <utilisateur idUtilisateur="u3">
        <!-- Utilisateur 3 : Samba -->
        <profil>
            <nom>Samba Diao</nom>
            <numeroDeTelephone>776951048</numeroDeTelephone>
            <imageProfil>http://profiles/samba.jpg</imageProfil>
            <statut>Hors ligne</statut>
        </profil>
        <contacts>
            <!-- Samba a Aboubakry comme contact -->
            <contact refIdUtilisateur="u1" />
            <!-- Samba a Modou comme contact -->
            <contact refIdUtilisateur="u2" />
        </contacts>
    </utilisateur>

    <utilisateur idUtilisateur="u5">
        <profil>
            <nom>Mandicou KA</nom>
            <numeroDeTelephone>777654321</numeroDeTelephone>
            <imageProfil>http://profiles/mba.jpg </imageProfil>
            <statut>Absent</statut>
        </profil>
        <contacts>
            <contact refIdUtilisateur="u1" />
            <contact refIdUtilisateur="u2" />
            <contact refIdUtilisateur="u3" />
        </contacts>
    </utilisateur>

    <groupe idGroupe="g1">
        <!-- Groupe : DS I FALL: Projet XML -->
        <nomGroupe>DS M FALL: Projet XML</nomGroupe>
        <membres>
            <!-- Aboubakry est membre du groupe -->
            <membre refIdUtilisateur="u1" />
            <!-- Modou est membre du groupe -->
            <membre refIdUtilisateur="u2" />
            <!-- Samba est membre du groupe -->
            <membre refIdUtilisateur="u3" />
        </membres>
        <messages>
            <!-- Référence au message m1 -->
            <refIdMessage refId="m1" />
            <!-- Référence au message m2 -->
            <refIdMessage refId="m2" />
        </messages>
    </groupe>

    <message idMessage="m1" typeContenu="texte" statut="envoye">
        <!-- Message m1 -->
        <contenu>Bonjour tout le monde!</contenu>
        <expediteur refIdUtilisateur="u1" />
        <horodatage>2023-07-02T12:00:00</horodatage>
        <destinataire refIdGroupe="g1" />
    </message>

    <message idMessage="m2" typeContenu="texte" statut="recu">
        <!-- Message m2 -->
        <contenu>Salut Abou!</contenu>
        <expediteur refIdUtilisateur="u2" />
        <horodatage>2023-07-02T12:01:00</horodatage>
        <destinataire refIdGroupe="g1" />
        <citation refIdMessage="m1" />
    </message>

    <message idMessage="m3" typeContenu="audio" statut="envoye">
        <!-- Message m3 -->
        <contenu>http://audio/greeting.mp3</contenu>
        <expediteur refIdUtilisateur="u3" />
        <horodatage>2023-07-02T12:02:00</horodatage>
        <destinataire refIdUtilisateur="u1" />
    </message>
</messagerie>
